
TESTS = punchcard_test.py arguscard_test.py bitfield_test.py word_test.py instruction_test.py instructions_test.py

default: tests

tests: $(TESTS)
	pytest punchcard_test.py 
	pytest arguscard_test.py 
	pytest bitfield_test.py 
	pytest word_test.py 
	pytest instruction_test.py 
	pytest instructions_test.py

