
OPCODES = {
    # General, masked or unmasked.
    "BA":   "Binary Add",
    "DA":   "Decimal Add",
    "WA":   "Word Add",
    "BS":   "Binary Subtract",
    "DS":   "Decimal Subtract",
    "WD":   "Word Difference",
    "NA":   "Not equal, Alphabetic",
    "NN":   "Not equal, Numeric",
    "LA":   "Less than or equal, Alphabetic",
    "LN":   "Less than or equal, Numeric",
    "TX":   "Transfer A to C",
    "TS":   "Transfer A to B and go to C",
    "HA":   "Half Add (mod 2)",
    "SM":   "Superimpose",
    "CP":   "Check Parity",
    # General, unmasked.
    "BM":   "Binary Multiply",
    "DM":   "Decimal Multiply",
    "BT":   "Binary Accumulate",
    "DT":   "Decimal Accumulate",
    "MT":   "Multiple Transfer",
    "TN":   "Transfer N words",
    "CC":   "Compute Orthocount",
    "IT":   "Item Transfer",
    "EBA":  "Extended Binary Add",
    "EBS":  "Extended Binary Subtract",
    "RT":   "Record Transfer",
    "MPC":  "Control Program",
    "PR":   "Proceed",
    # Inherent mask.
    "SWS":  "Shift Word and Substitute",
    "SPS":  "Shift Preserving sign and Substitute",
    "SWE":  "Shift Word and Extract",
    "SPE":  "Shift Preserving sign and Extract",
    "SSL":  "Shift and Select",
    "SS":   "Substitute",
    "EX":   "Extract",
    # Peripheral and print.
    "RF":   "Read Forward",
    "RB":   "Read Backward",
    "WF":   "Write Forward",
    "RW":   "Rewind",
    "PRA":  "Print Alphanumeric",
    "PRD":  "Print Decimal",
    "PRO":  "Print Octal",
    # Simulator.
    "S":    "Simulate",
    # Scientific.
    "FBA":  "Floating Binary Add",
    "FDA":  "Floating Decimal Add",
    "FBS":  "Floating Binary Subtract",
    "FDS":  "Floating Decimal Subtract",
    "FBD":  "Floating Binary Divide",
    "FDD":  "Floating Decimal Divide",
    "FBAU": "Floating Binary Add, Unnormalized",
    "FDAU": "Floating Decimal Add, Unnormalized",
    "FBSU": "Floating Binary Subtract, Unnormalized",
    "FDSU": "Floating Decimal Subtract, Unnormalized",
    "FBM":  "Floating Binary Multiply",
    "FDM":  "Floating Decimal Multiply",
    "ULD":  "Multiple Unload",
    "FBAE": "Floating Binary Add, Extended precision",
    "FBSE": "Floating Binary Subtract, Extended precision",
    "BD":   "Fixed Binary Divide",
    "DD":   "Fixed Decimal Divide",
    "FFN":  "Fixed-to-Floating Normalize",
    "FCON": "Conversion",
    "FLN":  "Floating Less than, Normalized",
    "FNN":  "Floating Not equal, Normalized"
}
